# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
version=0.1.0
group=me.squiddew.consoly

# Common
minecraft_version=26.3
mod_name=Consoly
mod_author=SquidDew (squiddew1)
mod_id=consoly
license=LGPL-3.0-only
description=A lightweight Minecraft mod that adds a fully customizable external console.
minecraft_version_range=[26.3, 26.4)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.3-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.19.5

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.3.0.1-beta
neoforge_loader_version_range=[4,)
