plugins {
    id 'java-library'
}

base {
    archivesName = "${mod_id}-${project.name}-${getFullVersion()}"
}

tasks.withType(Jar).configureEach {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${mod_name}" }
    }
}

String getFullVersion() {
    return "$version+$minecraft_version"
}